/*
 * boot.c - second stage of the Flashkeeper boot ROM: load the firmware
 * image from the SPI flash into the SPRAM, verify its signature, and
 * hand over to it.
 *
 * The firmware image is self-describing. Its header (the first 256
 * bytes of the image) contains:
 *
 *     offset 0x0:  magic, 0x57464B46 ("FKFW" little-endian)
 *     offset 0x4:  size, total image size in bytes (header included),
 *                  a multiple of 4
 *     offset 0x8:  type; 1 = signed ed25519 (IMG_SIGNED_ED25519),
 *                   verified below on every ROM; 0 = unsigned
 *                   (development image - booted only by development
 *                   ROMs built with ROM_ALLOW_UNSIGNED=1, see the
 *                   type check in boot_main)
 *     offset 0xA0: signer's ed25519 public key (32 bytes)
 *     offset 0xC0: ed25519 signature (64 bytes)
 *
 * The signature covers the 256-byte message
 *
 *     image[0x000..0x0C0)  ||  SHA-512(image[0x100..size))
 *
 * i.e. the header prefix (magic, size, type, reserved, signer key) as
 * written in the image, plus the SHA-512 digest of the payload.
 *
 * While portable, and much smaller in code size, TweetNaCl's ed25519 is
 * extremely slow on this core. Despite the smaller code size, it also 
 * still barely fits in the iCE40's available EBRs. Because of this, we
 * use libsodium's implementation instead, and we load and verify it from
 * flash rather than from the boot ROM (it is ~23 kB).
 *
 *   - fwsiglib is a fixed-size binary at a fixed flash offset (see
 *     LIB_FLASH below) and a fixed RAM address (FLIB_ADDR, a build
 *     constant generated by rom/tools/make_lib_inc.py);
 *   - The ROM copies it, hashes the RAM copy with SHA-512, and verifies
 *     the hash against FLIB_HASH, which is baked into the ROM. The
 *     fwsiglib binary is "pinned" to this hash, and the verification
 *     will fail with BadLib if the binary does not match FLIB_HASH,
 *	   unless ROM_ALLOW_UNSIGNED is defined and the image is unsigned.
 *   - The ROM itself does the SHA-512s (the system's single SHA-512 is
 *     the one compiled into this ROM; the firmware calls it too, see
 *     rom/tools/make_romapi.py)
 *   - The ROM then calls the library's single entry point
 *     (fk_lib_verify, through the trampoline in rom/libcall.S) for the
 *     ed25519 curve operations (pre-checks, [h](-A) + [S]B, pack)
 *   - The ROM does the final 32-byte compare (computed R' vs the
 *     signature's R).
 *
 * RAM layout (128 kB SPRAM, see rom/lib/lib.lds and
 * firmware/support/sections.lds):
 *
 *     [0,        IMG_MAX_SIZE)   firmware image (this file)
 *     [FLIB_ADDR, ...)           fwsiglib binary
 *     [0x1E000,  0x20000)        ROM/firmware stack
 *
 * The image must end before FLIB_ADDR; the library must end before the
 * stack; both are enforced at build time.
 *
 * The header layout and the signed message must stay in sync with
 * firmware/tools/sign.c and firmware/tools/mkflashimg.py.
 */
#include <stdint.h>
#include "../firmware/tweetnacl.h"
#include "../build/fwpk.inc" /* ROM_PK[32]: the only signer this ROM accepts */

/* fwsiglib constants (FLIB_ADDR, FLIB_SIZE, and the 64-byte
   SHA-512 hash initializer FLIB_HASH_INIT) are injected as -D flags by
   the build, generated by rom/tools/make_lib_inc.py from the linked library
   (see the Makefile). */
static const uint8_t FLIB_HASH[64] = FLIB_HASH_INIT;

/* The library's single entry point; the C symbol is provided by the
   trampoline in rom/libcall.S (see there for the ABI notes). h is
   scratch: the library reduces it in place (sc25519_reduce). */
extern int fk_lib_verify(const uint8_t *h, const uint8_t *pk,
                         const uint8_t *r, const uint8_t *s,
                         uint8_t *rout);

#define FW_IMAGE_FLASH ((const volatile uint32_t *) 0x01020000)
#define FW_IMAGE_RAM   ((volatile uint32_t *) 0x00000000)

/* Memory-mapped flash window of the flash library region (flash offset
   0x40000: the 256 kB point of the 512 kB flash, after the 128 kB image
   window; see the som_image rule in the Makefile). */
#define LIB_FLASH      ((const volatile uint32_t *) 0x01040000)
#define LIB_RAM        ((volatile uint32_t *) FLIB_ADDR)
#define reg_uart_clkdiv (*(volatile uint32_t*)0x02000004)
#define reg_uart_data (*(volatile uint32_t*)0x02000008)

#define IMG_MAGIC    0x57464B46u /* "FKFW" little-endian */
#define IMG_MIN_SIZE 0x104u      /* header + at least the 4-byte entry */
/* The image must not run into fwsiglib's slot. */
#define IMG_MAX_SIZE FLIB_ADDR
#define IMG_TYPE_SIGNED_ED25519 1u

/* 32-bit word indices of the header fields in the flash image window
   (byte offsets 0x0, 0x4, 0x8). */
#define IMG_FIELD_MAGIC 0
#define IMG_FIELD_SIZE 1
#define IMG_FIELD_TYPE 2

/* Header field offsets (see the file header; keep in sync with
   firmware/tools/sign.c). */
#define HDR_TYPE 0x08u
#define HDR_PK   0xA0u
#define HDR_SIG  0xC0u
#define IMG_PAYLOAD 0x100u

void print_hex(uint32_t v, int digits)
{
	for (int i = 7; i >= 0; i--) {
		char c = "0123456789abcdef"[(v >> (4*i)) & 15];
		if (c == '0' && i >= digits) continue;
		reg_uart_data = c;
		digits = i;
	}
}

void print(const char *p){
	while (*p)
		reg_uart_data = *(p++);
}

/* The ROM is freestanding (no libc headers, like the rest of it); the
   verify path needs only a few small copies. The volatile source pointer
   keeps GCC from speculating on the (legal) case where src is at
   address zero (SPRAM really is mapped at 0x0 in this design). */
static void copy_n(uint8_t *dst, const uint8_t *src, uint32_t n){
	volatile const uint8_t *vsrc = src;
	for (uint32_t i = 0; i < n; i++)
		dst[i] = *vsrc++;
}

// Load fwsiglib from flash and check its hash. Returns 0 on success.
static int load_fwsiglib(void){
	uint32_t i;
	uint8_t digest[crypto_hash_BYTES];

	for (i = 0; i < FLIB_SIZE / 4; i++)
		LIB_RAM[i] = LIB_FLASH[i];

	// If this ROM allows unsigned, AND the image is unsigned, we don't need
	// to verify the library either.
	#ifdef ROM_ALLOW_UNSIGNED
		if(FW_IMAGE_RAM[IMG_FIELD_TYPE] == 0) return 0;
	#endif

	// Hash the RAM copy
	crypto_hash(digest, (const uint8_t *) (uintptr_t) LIB_RAM, FLIB_SIZE);
	if (crypto_verify_64(digest, FLIB_HASH)){
		print("BadLib");
		return 1;
	}
	return 0;
}

int boot_main(void){
	reg_uart_clkdiv = 10; // 1 Mbaud
	print("\r\nBootROM ");

	#ifdef ROM_ALLOW_UNSIGNED
		// A development ROM can boot unverified code. Warn before we boot (or fail).
		print("Insecure ");
	#endif

	uint32_t magic = FW_IMAGE_FLASH[IMG_FIELD_MAGIC];
	uint32_t size  = FW_IMAGE_FLASH[IMG_FIELD_SIZE];
	uint32_t type  = FW_IMAGE_FLASH[IMG_FIELD_TYPE];

	/* The flash is untrusted: refuse anything that is not a sane image
	   (a blank chip reads as all 0xFF, which fails the magic check). */
	if (magic != IMG_MAGIC){
		print("BadMagic ");
		print_hex(magic, 8);
		return 1;
	}
	if (size < IMG_MIN_SIZE || size > IMG_MAX_SIZE || (size & 3u)){
		print("BadSize");
		return 1;
	}

	// Copy the image from flash into RAM. Not verified yet on the
	// signed path (checked below); booted as-is on the unsigned one.
	for (uint32_t i = 0; i < size / 4; i++){
		uint32_t w = FW_IMAGE_FLASH[i];
		FW_IMAGE_RAM[i] = w;
	}

	// Load and verify the fwsiglib ed25519 binary from its flash region into RAM
	if (load_fwsiglib())
		return 4;

	if (type != IMG_TYPE_SIGNED_ED25519){
		#ifndef ROM_ALLOW_UNSIGNED
			print("BadType");
			return 1;
		#else
			if (type != 0u){ // if it isn't type 1 OR type 0
				print("BadType");
				return 1;
			}
			print("Unverified OK");
			return 0;
		#endif
	}

	print("Verify ");

	// Pointer to the image in RAM. Not written to after the copy above.
	const uint8_t *img = (const uint8_t *) (uintptr_t) FW_IMAGE_RAM;

	// Before attempting actual verification, confirm the image at least claims to be for the right PK
	if (crypto_verify_32(img + HDR_PK, ROM_PK)){
		print("BadPk");
		return 2;
	}

	// ed25519 defines h = SHA-512(R || A || M). M is our 256-byte message to be verified
	// (header prefix || payload digest). fk_lib_verify takes h pre-hashed, so we prepare h here.
	uint8_t digest[crypto_hash_BYTES];
	uint8_t m[HDR_SIG + crypto_hash_BYTES]; // the 256-byte signed message M
	uint8_t hbuf[crypto_sign_BYTES / 2 + crypto_sign_PUBLICKEYBYTES + sizeof(m)]; // R || A || M: 320 bytes
	uint8_t h[crypto_hash_BYTES];
	uint8_t rout[crypto_sign_BYTES / 2];

	// Hash the image payload into digest
	crypto_hash(digest, img + IMG_PAYLOAD, size - IMG_PAYLOAD);

	// copy image header, up to and including signer PK, into the beginning of m
	copy_n(m, img, HDR_SIG);

	// copy digest into the end of m
	copy_n(m + HDR_SIG, digest, crypto_hash_BYTES);

	// Copy the signature R (first half of the signature), the expected public key, and m into hbuf in that order
	copy_n(hbuf, img + HDR_SIG, crypto_sign_BYTES / 2); /* R */
	copy_n(hbuf + crypto_sign_BYTES / 2, ROM_PK, crypto_sign_PUBLICKEYBYTES);
	copy_n(hbuf + crypto_sign_BYTES / 2 + crypto_sign_PUBLICKEYBYTES, m, sizeof(m));

	// Hash hbuf into h
	crypto_hash(h, hbuf, sizeof(hbuf));

	// If verify fails, or outputs an R not matching the image's signature's R, reject as bad signature
	if (fk_lib_verify(h, img + HDR_PK, img + HDR_SIG,
	                   img + HDR_SIG + crypto_sign_BYTES / 2, rout) != 0 ||
	    crypto_verify_32(rout, img + HDR_SIG)){
		print("BadSig");
		return 3;
	}
	print("OK");
	return 0;
}
