#!/usr/bin/env python3
"""
Generate the boot ROM's signer key header (build/fwpk.inc) from a
32-byte ed25519 public key file (firmware/keys/pk.key, created by
firmware/tools/genkey). The ROM accepts only signatures from this key
(see rom/boot.c).

Usage: make_pk_inc.py <pk.key> <out.inc>
"""
import sys

def main(pk_path, out_path):
    with open(pk_path, 'rb') as f:
        pk = f.read()
    assert len(pk) == 32, \
        f"{pk_path} is {len(pk)} bytes; expected a 32-byte ed25519 public key"
    with open(out_path, 'w') as f:
        f.write("/* Generated by rom/tools/make_pk_inc.py from %s - do not edit.\n"
                " * The only signer the boot ROM accepts (see rom/boot.c). */\n"
                "static const uint8_t ROM_PK[32] = {\n    "
                % pk_path
                + ", ".join("0x%02x" % b for b in pk)
                + "\n};\n")
    print("fwpk: wrote %s (32-byte signer key)" % out_path)

if __name__ == '__main__':
    assert len(sys.argv) == 3, __doc__
    main(sys.argv[1], sys.argv[2])
