# This config is to run with jekyll locally:
#  to preview your changes, do 'jekyll serve --config docs/_config-local.yml'
theme: "just-the-docs"
color_scheme: dark
heading_anchors: true
aux_links:
  "Source":
    - "https://git.15h.org/Flashkeeper/flashkeeper"
  "Join us on Matrix!":
    - "https://matrix.to/#/#flashkeeper:matrix.org"
aux_links_new_tab: true

title: Flashkeeper

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# For local development, use an empty baseurl
baseurl: ""  # This ensures paths resolve correctly during local testing

# Include files and directories
include:
  - images

# Specify the source directory
source: docs

# Configure defaults for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
