# This config is to run with jekyll locally:
#  to preview your changes, do 'jekyll serve --config docs/_config-local.yml'
theme: "just-the-docs"
color_scheme: dark
heading_anchors: true
aux_links:
  "Flashkeeper on GitHub":
    - "https://github.com/linuxboot/flashkeeper"
aux_links_new_tab: true

title: Flashkeeper - Wiki

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/linuxboot/flashkeeper"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "edit"

# For local development, use an empty baseurl
baseurl: ""  # This ensures paths resolve correctly during local testing

# Include files and directories
include:
  - images

# Specify the source directory
source: docs

# Configure defaults for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
